[database]
# Amount of queue items to do per drain
maxQueueSize = 50
# Amount of time to wait for queue to reach maxQueueSize
queueTimeoutSec = 5

[search]
# Number of actions to show per page
pageSize = 8

[color]
# Colors in hex format
primary = "#009688"
primaryVariant = "#52c7b8"
secondary = "#1e88e5"
secondaryVariant = "#6ab7ff"
light = "#c5d6f0"

[actions]
# Blacklists - blacklisted things will not be logged in the database
# Example - Prevent all actions with stone or bat as the object from being logged
# objectBlacklist = [
#   "minecraft:stone",
#   "minecraft:bat"
# ]

# Blacklists action types. Ex: "block-break", "entity-kill"
typeBlacklist = []
# Blacklists worlds/dimensions. Ex: "mincraft:the_end", "minecraft:overworld"
worldBlacklist = []
# Blacklists objects (Items, Mobs, Blocks). Ex: "minecraft:cobblestone", "minecraft:blaze"
objectBlacklist = []
# Blacklists sources. Ex: "lava", "gravity", "fire", "fall"
sourceBlacklist = []

[networking]
# This section relates to Ledger's ability to interact with client mods for ease of use
# Networking is enabled by default but you can disable and control it here

# Change to true to allow Ledger client mod packets
networking = true
# Controls whether a mod should be allowed or denyed by default
allowByDefault = true
# Whitelists mods to bypass the allowByDefault. Ex: ["my_client", "ledger_mod"]
modWhitelist = []
# Disallows mods even if allowByDefault is enabled. Ex: ["my_client", "ledger_mod"]
modBlacklist = []