package com.github.quiltservertools.ledger.utility

object Sources {
    const val FIRE = "fire"
    const val GRAVITY = "gravity"
    const val EXPLOSION = "explosion"
    const val PLAYER = "player"
    const val BROKE = "broke"
    const val DECAY = "decay"
    const val MELT = "melt"
    const val FROST_WALKER = "frost_walker"
    const val REDSTONE = "redstone"
    const val FLUID = "fluid"
    const val TRAMPLE = "trample"
    const val EXTINGUISH = "extinguish"
    const val INTERACT = "interact"
    const val GROW = "grow"
    const val SNOW_GOLEM = "snow_golem"
    const val SPONGE = "sponge"
    const val PORTAL = "portal"
    const val EQUIP = "equip"
    const val REMOVE = "remove"
    const val ROTATE = "rotate"
    const val UNKNOWN = "unknown"
}
