package com.github.quiltservertools.ledger.utility

object Sources {
    const val FIRE = "fire"
    const val GRAVITY = "gravity"
    const val EXPLOSION = "explosion"
    const val PLAYER = "player"
    const val BROKE = "broke"
    const val DECAY = "decay"
    const val DRY = "dry"
    const val WET = "wet"
    const val MELT = "melt"
    const val FROST_WALKER = "frost_walker"
    const val REDSTONE = "redstone"
    const val FLUID = "fluid"
    const val FILL = "fill"
    const val DRAIN = "drain"
    const val DRIP = "drip"
    const val SNOW = "snow"
    const val REMOVE = "remove"
    const val TRAMPLE = "trample"
    const val EXTINGUISH = "extinguish"
    const val INSERT = "insert"
    const val INTERACT = "interact"
    const val CONSUME = "consume"
    const val GROW = "grow"
    const val SNOW_GOLEM = "snow_golem"
    const val SPONGE = "sponge"
    const val PORTAL = "portal"
    const val COMMAND = "command"
    const val UNKNOWN = "unknown"
}
