name: Release Documentation

on:
  release:
    types: [published]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      -   name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
      -   name: Set up python 3
          uses: actions/setup-python@v5
          with:
            python-version: 3.x
      -   name: Install mkdocs and mike
          run: pip install mkdocs-material mike
      -   name: Set up git credentials
          uses: oleksiyrudenko/gha-git-credentials@v2-latest
          with:
            global: true
            token: ${{ secrets.USER_TOKEN }}
      -   name: Deploy docs
          run: mike deploy --push --update-aliases ${{ github.event.release.tag_name }} latest
